services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:80"   # test web mapped to 81 to avoid colliding with main stack
    volumes:
      - ./src:/var/www/html

  db:
    image: mariadb:11.4
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: novaccess
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
      - "3307:3306"  # expose 3307 to avoid colliding with main stack
    volumes:
      - ./data_test:/var/lib/mysql
      - ./01-init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./02-testdata.sql:/docker-entrypoint-initdb.d/02-testdata.sql:ro

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
